services:
  db:
    image: postgres:15-alpine
    container_name: vkahub-db
    env_file:
      - ./server/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - vkahub-net

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: vkahub-api
    depends_on:
      - db
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    volumes:
      - ./server/reports:/app/reports
      - ./server/certificates:/app/certificates
      - ./server/team-images:/app/team-images
      - ./server/user-avatars:/app/user-avatars
      - ./server/bugs:/app/bugs
      - ./server/events:/app/events
      - ./server/attachments:/app/attachments
    restart: unless-stopped
    networks:
      - vkahub-net

  client-builder:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vkahub-client-builder
    volumes:
      - ./client-files:/dist
    command: sh -c "npm run build"

  admin:
    image: dpage/pgadmin4:6.19
    container_name: vkahub-admin
    depends_on:
      - db
    env_file:
      - ./server/.env
    ports:
      - "5001:5001"
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - vkahub-net
    restart: unless-stopped

networks:
  vkahub-net:
    name: vkahub-net
    driver: bridge

volumes:
  db_data:
  pgadmin: