services:
  db:
    image: postgres:15-alpine
    container_name: vkahub-db
    env_file:
      - ./server/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vkahub-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vkahub"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: vkahub-api
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server/static:/app/static
    networks:
      - vkahub-net

  client-builder:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vkahub-client-builder
    volumes:
      - ./client-files:/dist
    command: sh -c "npm run build"

  admin:
    image: dpage/pgadmin4:6.19
    container_name: vkahub-admin
    env_file:
      - ./server/.env
    ports:
      - "5001:5001"
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - vkahub-net
    restart: always

networks:
  vkahub-net:
    name: vkahub-net
    driver: bridge

volumes:
  db_data:
  pgadmin: