database:
  username: postgres
  password: postgres
  host: db
  port: 5432
  databaseName: vkahub
  sslMode: false

migrations:
  enable: true
  connUri: postgres://postgres:postgres@db:5432/vkahub?sslmode=disable
  dirUrl: file:///app/migrations

authorizer:
  accessSecretKey: access-vkahub-secret-vkahub-key
  refreshSecretKey: refresh-vkahub-secret-vkahub-key

onliner:
  address: http://redis:6379
  password: 
  databaseNum: 0

cloud:
  address: cloud:9000
  username: minio-root
  password: minio-root
  enableSSL: false
  mainBucket: vkahub-bucket