database:
  username: postgres
  password: postgres
  host: db
  port: 5432
  databaseName: vkahub
  sslMode: false

migrations:
  enable: true
  connUri: postgres://postgres:postgres@db:5432/vkahub?sslmode=disable
  dirUrl: file:///app/migrations